# Site settings
title: Sahhhm's Code and Beard Blog
email: samorgan@huskers.unl.edu
description: > # this means to ignore newlines until "baseurl:"
  This blog will follow Sam's progress through Omaha Code School and beyond as well as the occasional update on his gnarly beard'.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  Sahhm

# Build settings
markdown: redcarpet
